#pragma once

enum AudioFlag {
	AF_ActivateSwitchWheelAudio = 0,
	AF_AllowCutsceneOverScreenFade = 1,
	AF_AllowForceRadioAfterRetune = 2,
	AF_AllowPainAndAmbientSpeechToPlayDuringCutscene = 3,
	AF_AllowPlayerAIOnMission = 4,
	AF_AllowPoliceScannerWhenPlayerHasNoControl = 5,
	AF_AllowRadioDuringSwitch = 6,
	AF_AllowRadioOverScreenFade = 7,
	AF_AllowScoreAndRadio = 8,
	AF_AllowScriptedSpeechInSlowMo = 9,
	AF_AvoidMissionCompleteDelay = 10,
	AF_DisableAbortConversationForDeathAndInjury = 11,
	AF_DisableAbortConversationForRagdoll = 12,
	AF_DisableBarks = 13,
	AF_DisableFlightMusic = 14,
	AF_DisableReplayScriptStreamRecording = 15,
	AF_EnableHeadsetBeep = 16,
	AF_ForceConversationInterrupt = 17,
	AF_ForceSeamlessRadioSwitch = 18,
	AF_ForceSniperAudio = 19,
	AF_FrontendRadioDisabled = 20,
	AF_HoldMissionCompleteWhenPrepared = 21,
	AF_IsDirectorModeActive = 22,
	AF_IsPlayerOnMissionForSpeech = 23,
	AF_ListenerReverbDisabled = 24,
	AF_LoadMPData = 25,
	AF_MobileRadioInGame = 26,
	AF_OnlyAllowScriptTriggerPoliceScanner = 27,
	AF_PlayMenuMusic = 28,
	AF_PoliceScannerDisabled = 29,
	AF_ScriptedConvListenerMaySpeak = 30,
	AF_SpeechDucksScore = 31,
	AF_SuppressPlayerScubaBreathing = 32,
	AF_WantedMusicDisabled = 33,
	AF_WantedMusicOnMission = 34
};

char* _audioFlags[] = {
	"ActivateSwitchWheelAudio",
	"AllowCutsceneOverScreenFade",
	"AllowForceRadioAfterRetune",
	"AllowPainAndAmbientSpeechToPlayDuringCutscene",
	"AllowPlayerAIOnMission",
	"AllowPoliceScannerWhenPlayerHasNoControl",
	"AllowRadioDuringSwitch",
	"AllowRadioOverScreenFade",
	"AllowScoreAndRadio",
	"AllowScriptedSpeechInSlowMo",
	"AvoidMissionCompleteDelay",
	"DisableAbortConversationForDeathAndInjury",
	"DisableAbortConversationForRagdoll",
	"DisableBarks",
	"DisableFlightMusic",
	"DisableReplayScriptStreamRecording",
	"EnableHeadsetBeep",
	"ForceConversationInterrupt",
	"ForceSeamlessRadioSwitch",
	"ForceSniperAudio",
	"FrontendRadioDisabled",
	"HoldMissionCompleteWhenPrepared",
	"IsDirectorModeActive",
	"IsPlayerOnMissionForSpeech",
	"ListenerReverbDisabled",
	"LoadMPData",
	"MobileRadioInGame",
	"OnlyAllowScriptTriggerPoliceScanner",
	"PlayMenuMusic",
	"PoliceScannerDisabled",
	"ScriptedConvListenerMaySpeak",
	"SpeechDucksScore",
	"SuppressPlayerScubaBreathing",
	"WantedMusicDisabled",
	"WantedMusicOnMission"
};